#!/usr/bin/env bash

version_list=(v1-beta)
selection=0

while true; do
  clear
  echo "Select version(note: beta unstable and used for testing new features):"
  echo
  
  for i in "${!version_list[@]}"; do
    if [ "$i" -eq "$selection" ]; then
      echo -e "> \e[7m${version_list[$i]}\e[0m"
    else
      echo "  ${version_list[$i]}"
    fi
  done

  echo
  echo "< (↓/j)Down, (↑/k)Up, (Enter)Install >"

  read -r -n 1 keycode
  case "$keycode" in
    [$'\e[B'Jj]*) # Down arrow
      ((selection++))
      selection=$((selection >= ${#version_list[@]} ? 0 : selection))
      ;;
    [$'\e[A'Kk]*) # Up arrow
      ((selection--))
      selection=$((selection < 0 ? ${#version_list[@]} - 1 : selection))
      ;;
    '') # Enter
      bash <(curl https://raw.githubusercontent.com/qrcpp/foxvim/main/${version_list[selection]}/build)
      exit
      ;;
  esac
done
