#!/usr/bin/env bash

version=(v1-beta)
select=0
error=0

while true; do
  clear
  echo "Select version(note: beta unstable and used for testing new features):"
  echo
  
  for index in "${!version[@]}"; do
    if [ "$index" -eq "$select" ]; then
      echo -e "> \e[7m${version[$index]}\e[0m"
    else
      echo "  ${version[$index]}"
    fi
  done

  echo
  echo "< (↓/j)Down, (↑/k)Up, (Enter)Install >"

  if [ "$error" -eq 1 ]; then
    echo "[!] illegal key -- $key"
    error=0
  fi

  read -rsn1 key
  case "$key" in
    [AKk]*)
      ((select--))
      [ "$select" -lt 0 ] && select=$((${#version[@]} - 1))
      ;;
    [Bjj]*)
      ((select++))
      [ "$select" -ge ${#version[@]} ] && select=0
      ;;
    '')
      echo
      bash <(curl https://raw.githubusercontent.com/qrcpp/foxvim/main/${version[select]}/build)
      exit
      ;;
    *)
      error=1
      ;;
  esac
done
